"""empty message

Revision ID: za9e5a6d47e1
Revises: 5594cff9fef8
Create Date: 2023-01-24 09:48:38.270952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'za9e5a6d47e1'
down_revision = '5594cff9fef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=128), nullable=False),
    sa.Column('datePublished', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )

    op.create_table('sentiments',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pos', sa.Float(), nullable=False),
    sa.Column('neg', sa.Float(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('articles')
    op.drop_table('sentiments')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
