"""empty message

Revision ID: 2d33cb8cfb00
Revises: fef817fdacd7
Create Date: 2022-02-19 23:53:52.972200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d33cb8cfb00'
down_revision = 'fef817fdacd7'
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(op.f('ix_predictions_date'), 'predictions', ['date'], unique=False)
    op.create_unique_constraint(None, 'stock_model', ['id'])
    op.add_column('task', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'date')
    op.drop_constraint(None, 'stock_model', type_='unique')
    op.drop_index(op.f('ix_predictions_date'), table_name='predictions')
    # ### end Alembic commands ###
