"""empty message

Revision ID: 5594cff9fef8
Revises: e0532204a794
Create Date: 2022-02-23 15:09:13.306113

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '5594cff9fef8'
down_revision = 'e0532204a794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('pomegranate', 'default', name="model_types", create_type=False, default='default')
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column('stock_model', sa.Column('model_type', enum))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_model', 'model_type')
    ENUM(name="model_types").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
