"""empty message

Revision ID: e0532204a794
Revises: 2d33cb8cfb00
Create Date: 2022-02-20 14:50:13.122293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0532204a794'
down_revision = '2d33cb8cfb00'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('task', sa.Column('job_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'task', ['job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_column('task', 'job_id')
    # ### end Alembic commands ###
