"""empty message

Revision ID: eb645245f53a
Revises: 
Create Date: 2021-02-13 08:52:18.952810

"""
from alembic import op
import sqlalchemy as sa
import app.main.utils as utils


# revision identifiers, used by Alembic.
revision = 'eb645245f53a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    # ### end Alembic commands ###

    (ticker_list, _) = utils.getTickerList(start=1, end=10)
    for ticker in ticker_list:
        table_name = ticker.lower()
        op.create_table(table_name,
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('date', sa.Date(), nullable=True),
            sa.Column('open', sa.Float(), nullable=True),
            sa.Column('high', sa.Float(), nullable=True),
            sa.Column('low', sa.Float(), nullable=True),
            sa.Column('close', sa.Float(), nullable=True),
            sa.Column('adj_close', sa.Float(), nullable=True),
            sa.Column('volume', sa.Float(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f(f"ix_{table_name}_bar_date"), table_name, ['date'], unique=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###

    (ticker_list, _) = utils.getTickerList(start=1, end=10)
    for ticker in ticker_list:
        table_name = ticker.lower()
        op.drop_index(op.f(f"ix_{table_name}_bar_date"), table_name=table_name)
        op.drop_table(table_name)
