"""empty message

Revision ID: fa9e5a6d47e1
Revises: 88b1541b5308
Create Date: 2022-01-24 09:48:38.270952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa9e5a6d47e1'
down_revision = '88b1541b5308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_model', sa.Column('observation_period', sa.Integer(), nullable=True))
    op.drop_column('stock_model', 'possible_outcomes')
    op.drop_column('stock_model', 'features')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_model', sa.Column('features', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_model', sa.Column('possible_outcomes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('stock_model', 'observation_period')
    # ### end Alembic commands ###
